shellcheck: Fix issues and add runner

diff --git a/test/debug/run b/test/debug/run
--- a/test/debug/run
+++ b/test/debug/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Always run the tests from this script's folder
-cd $(dirname "$0") || exit 1
+cd "$(dirname "$0")" || exit 1
 
 # Read default configuration
 source ../_include.sh
@@ -10,16 +10,16 @@ source ../_include.sh
 for file_path in ${@:-../parsing/*.sed}
 do
 
-    file=$(basename $file_path)
+    file=$(basename "$file_path")
     output_file=$file.txt
 
     # Only test *.gnu.sed files when using GNU sed
-    test ${file%.gnu.sed} != $file && test "$sed" != 'gsed' && continue
+    test "${file%.gnu.sed}" != "$file" && test "$sed" != 'gsed' && continue
 
     test_message "Testing ${file%.sed}"
 
     # Run the debugger and save the results
-    echo "$text" | $sedsed --debug -f $file_path > $output_file || failed=1
+    echo "$text" | $sedsed --debug -f "$file_path" > "$output_file" || failed=1
 done
 
 tests_git_status
diff --git a/test/parsing/run b/test/parsing/run
--- a/test/parsing/run
+++ b/test/parsing/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Always run the tests from this script's folder
-cd $(dirname "$0") || exit 1
+cd "$(dirname "$0")" || exit 1
 
 # Read default configuration
 source ../_include.sh
@@ -11,14 +11,14 @@ for file in ${@:-*.sed}
 do
 
     # Only test *.gnu.sed files when using GNU sed
-    test ${file%.gnu.sed} != $file && test "$sed" != 'gsed' && continue
+    test "${file%.gnu.sed}" != "$file" && test "$sed" != 'gsed' && continue
 
     test_message "Testing ${file%.sed}"
 
     # Run the same sed script in sed and sedsed -d, results must be equal
-    echo "$text" | $sed -f $file > $sed_output || failed=1
-    echo "$text" | $sedsed -d --_stdout-only -f $file > $sedsed_output || failed=1
-    diff -U1 $sed_output $sedsed_output || failed=1
+    echo "$text" | $sed -f "$file" > "$sed_output" || failed=1
+    echo "$text" | $sedsed -d --_stdout-only -f "$file" > "$sedsed_output" || failed=1
+    diff -U1 "$sed_output" "$sedsed_output" || failed=1
 done
 
 tests_git_status
