test: Now exitcode=1 when any test fails
It's important that when one or more tests fail, the runner script
returns with exit code 1 to make it clear that there was a failure.

It's specially important for the CI, so the job will fail accordingly.

diff --git a/test/debug/run b/test/debug/run
--- a/test/debug/run
+++ b/test/debug/run
@@ -19,7 +19,8 @@ do
     test_message "Testing ${file%.sed}"
 
     # Run the debugger and save the results
-    echo "$text" | $sedsed --debug -f $file_path > $output_file
+    echo "$text" | $sedsed --debug -f $file_path > $output_file || failed=1
 done
 
 tests_git_status
+tests_exit
diff --git a/test/emudebug/run b/test/emudebug/run
--- a/test/emudebug/run
+++ b/test/emudebug/run
@@ -16,7 +16,8 @@ do
     test_message "Testing ${file%.sed}"
 
     # Run the sed emulator debugger and save the results
-    echo "$text" | $sedsed --emudebug -f $file_path > $output_file
+    echo "$text" | $sedsed --emudebug -f $file_path > $output_file || failed=1
 done
 
 tests_git_status
+tests_exit
